export enum AccessoryType {
  CarbonDioxideSensor = 'CarbonDioxideSensor',
  CarbonMonoxideSensor = 'CarbonMonoxideSensor',
  ContactSensor = 'ContactSensor',
  HeaterCooler = 'HeaterCooler',
  HumiditySensor = 'HumiditySensor',
  LeakSensor = 'LeakSensor',
  Lightbulb = 'Lightbulb',
  LightSensor = 'LightSensor',
  LockMechanism = 'LockMechanism',
  MotionSensor = 'MotionSensor',
  OccupancySensor = 'OccupancySensor',
  Outlet = 'Outlet',
  SecuritySystem = 'SecuritySystem',
  SmokeSensor = 'SmokeSensor',
  Switch = 'Switch',
  TemperatureSensor = 'TemperatureSensor',
  Thermostat = 'Thermostat',
}

export enum CharacteristicKey {
  Active = 'Active',
  BatteryLevel = 'BatteryLevel',
  Brightness = 'Brightness',
  CarbonDioxideDetected = 'CarbonDioxideDetected',
  CarbonDioxideLevel = 'CarbonDioxideLevel',
  CarbonDioxidePeakLevel = 'CarbonDioxidePeakLevel',
  CarbonMonoxideDetected = 'CarbonMonoxideDetected',
  CarbonMonoxideLevel = 'CarbonMonoxideLevel',
  CarbonMonoxidePeakLevel = 'CarbonMonoxidePeakLevel',
  ColorTemperature = 'ColorTemperature',
  ContactSensorState = 'ContactSensorState',
  CoolingThresholdTemperature = 'CoolingThresholdTemperature',
  CurrentAmbientLightLevel = 'CurrentAmbientLightLevel',
  CurrentHeaterCoolerState = 'CurrentHeaterCoolerState',
  CurrentHeatingCoolingState = 'CurrentHeatingCoolingState',
  CurrentRelativeHumidity = 'CurrentRelativeHumidity',
  CurrentTemperature = 'CurrentTemperature',
  HeatingThresholdTemperature = 'HeatingThresholdTemperature',
  Hue = 'Hue',
  LeakDetected = 'LeakDetected',
  LockCurrentState = 'LockCurrentState',
  LockPhysicalControls = 'LockPhysicalControls',
  LockTargetState = 'LockTargetState',
  MotionDetected = 'MotionDetected',
  OccupancyDetected = 'OccupancyDetected',
  On = 'On',
  OutletInUse = 'OutletInUse',
  RotationSpeed = 'RotationSpeed',
  Saturation = 'Saturation',
  SecuritySystemCurrentState = 'SecuritySystemCurrentState',
  SecuritySystemTargetState = 'SecuritySystemTargetState',
  SmokeDetected = 'SmokeDetected',
  StatusActive = 'StatusActive',
  StatusFault = 'StatusFault',
  StatusLowBattery = 'StatusLowBattery',
  StatusTampered = 'StatusTampered',
  SwingMode = 'SwingMode',
  TargetHeaterCoolerState = 'TargetHeaterCoolerState',
  TargetHeatingCoolingState = 'TargetHeatingCoolingState',
  TargetRelativeHumidity = 'TargetRelativeHumidity',
  TargetTemperature = 'TargetTemperature',
  TemperatureDisplayUnits = 'TemperatureDisplayUnits',
}

export enum TemperatureUnits {
  CELSIUS = 'C',
  FAHRENHEIT = 'F',
}